# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build und Test

on:  # Trigger: Hier wird festgelegt, wann die Pipeline ausgeführt wird
  push:
    branches: [ "main" ]
    paths:
      - M008_Bankkonto
      - M008_BankkontoTests
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Aktiviert einen Button, mit dem die Pipeline per Hand ausgeführt werden kann

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
