# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build und Test

on:  # Trigger: Hier wird festgelegt, wann die Pipeline ausgef端hrt wird
  push:
    branches: [ "main" ]
    paths:
      - M008_Bankkonto
      - M008_BankkontoTests
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Aktiviert einen Button, mit dem die Pipeline per Hand ausgef端hrt werden kann

jobs:  # Was in der Pipeline passieren soll
  build:
    runs-on: windows-latest  # Die VM auf dem der Code ausgef端hrt wird
    
    steps:
    - name: Sourcecode holen
      uses: actions/checkout@v4  # Ein eigenes Git-Repo, mit dem zu Ausf端hrenden Code
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0

    - name: Projekt Build
      run: dotnet build ./M008_Bankkonto/M008_Bankkonto.csproj

    - name: Projekt Test
      run: dotnet test ./M008_BankkontoTests/M008_BankkontoTests.csproj

    - name: Projekt .exe erzeugen
      run: dotnet publish ./M008_Bankkonto/M008_Bankkonto.csproj --configuration Release --runtime win-x64 --self-contained true --property:PublishSingleFile=true --output ./publish --property:IncludeAllContentForSelfExtract=true

    - name: Release erzeugen
      uses: softprops/action-gh-release@v2
      with:
        name: Release 1
        files: publish/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
