
name: Build und Test

on:  # Trigger: Hier wird festgelegt, wann die Pipeline ausgef端hrt wird
  workflow_dispatch:  # Aktiviert einen Button, mit dem die Pipeline per Hand ausgef端hrt werden kann

jobs:  # Was in der Pipeline passieren soll
  build:
    runs-on: windows-latest  # Die VM auf dem der Code ausgef端hrt wird
    
    steps:
    - name: Sourcecode holen
      uses: actions/checkout@v4  # Ein eigenes Git-Repo, mit dem zu Ausf端hrenden Code
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 4.8

    - name: Dependencies laden
      run: dotnet restore ./M009_WPF/M009_WPF.csproj

    - name: Projekt Build
      run: dotnet build ./M009_WPF/M009_WPF.csproj
      
    - name: Projekt Test
      run: dotnet test ./M009_WPFTests/M009_WPFTests.csproj
